insert into properties(prpty_name, prpty_price, prpty_size, prpty_location, prpty_saletype_id, prpty_nbhd_id, prpty_description, prpty_latitude, prpty_longitude, images, prpty_type_id, category_id, home_details_id)
values('Single Family House in Kigobe', 1000000, 2000, 'Kigobe, Avenue kigobe, numero 1', 2, 2, 'Nestled in a quiet suburban neighborhood, this 3-bedroom, 2-bathroom cottage offers a cozy retreat with a warm, rustic charm. The house boasts hardwood floors, a brick fireplace, and a renovated kitchen with modern appliances. A large backyard with mature trees provides ample space for outdoor activities or gardening. Perfect for families or couples seeking a peaceful living space.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.3594706334510493, 29.384388098333485, 'OrtusRealty/listings/img1_1.jpg,OrtusRealty/listings/img1_2.jpg,OrtusRealty/listings/img1_3.jpg,OrtusRealty/listings/img29.jpg,OrtusRealty/listings/img19_1.jpg', 2, 3, 'home1'),

('Farming land in Nyabihanga', 60000000, 5090, 'Nyabihanga, Kibungere', 1, 7, 'This 5090 sqft parcel of prime agricultural land is ideal for growing crops year-round, thanks to its rich, fertile soil and excellent water availability. Located near a major irrigation canal, the land includes access to a reliable water source. The flat terrain is perfect for mechanized farming, and the property comes with partial fencing and easy access to nearby markets.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.409657835725445, 29.821076591889085, 'OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg', 1, 1, ''),

('Construction Site in Karera(Looking For Investors)', 20000000, 3000, 'Karera 1, Avenue karera, numero 1', 3, 4, 'This prime 3000 sqft downtown site is being transformed into a multi-story, mixed-use commercial building. The development will feature office spaces on the upper floors, retail shops on the ground level, and underground parking. The modern design includes large glass facades, sustainable building materials, and green spaces integrated throughout the property. Positioned in a high-traffic area with easy access to public transportation, this site is ideal for businesses seeking a dynamic urban location.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.4218719969720492, 29.894118486606473, 'OrtusRealty/listings/img3_1.jpg,OrtusRealty/listings/img3_1.jpg,OrtusRealty/listings/img3_1.jpg,OrtusRealty/listings/img3_1.jpg,OrtusRealty/listings/img3_1.jpg', 3, 2, ''),

('Farming project in Bukeye', 100000000, 7610, 'Bukeye, Gaharo', 3, 9, 'This innovative agricultural project utilizes a hydroponic system to grow vegetables in a controlled, soil-free environment. Located on a 7610 sqft farm, the project focuses on producing high-yield crops like lettuce, spinach, and tomatoes, using significantly less water than traditional farming methods. The project aims to supply local markets and restaurants with fresh, sustainably grown produce while reducing its carbon footprint through energy-efficient greenhouse practices.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.1715861280009703, 29.660651231499706, 'OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg', 4, 1, ''),

('Villa in Kiriri', 550000000, 3800, 'Kiriri, Avenue kiriri, numero 1', 1, 3, 'This stunning 5-bedroom, 4-bathroom villa features sleek modern architecture with floor-to-ceiling windows, offering breathtaking views of the surrounding landscape. The property includes a private pool, spacious garden, and an open-plan living area that seamlessly blends indoor and outdoor spaces. Located in an exclusive gated community, the villa provides complete privacy, security, and luxury.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.390880855979182, 29.387623168008712, 'OrtusRealty/listings/img5_1.jpg,OrtusRealty/listings/img29.jpg,OrtusRealty/listings/img1_3.jpg,OrtusRealty/listings/img1_2.jpg,OrtusRealty/listings/img5_5.jpg', 2, 3, 'home2'),

('Commercial Land at Kugasaka', 10000000, 6300, 'Kugasaka, Rue numero 1', 2, 6, 'This 6300 sqft parcel is located in the heart of the citys bustling commercial district, offering excellent visibility and high foot traffic. Zoned for mixed-use development, this land is ideal for retail, office buildings, or hotels. With easy access to public transportation and major highways, the site provides a perfect opportunity for investors looking to build high-demand commercial facilities.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -2.9130804518785918, 29.819527868994015, 'OrtusRealty/listings/img7.jpg,OrtusRealty/listings/img7.jpg,OrtusRealty/listings/img7.jpg,OrtusRealty/listings/img7.jpg,OrtusRealty/listings/img7.jpg', 1, 2, ''),

('Agricultural Land for Agroforestry Project in Giheta', 30000000, 7240, 'Giheta, Muremera', 3, 8, 'Located on 7240 sqft of rural land, this agroforestry project integrates tree planting with traditional crop cultivation to enhance biodiversity and improve soil health. The project primary focus is on growing hardwood trees and fruit-bearing trees alongside staple crops like corn and beans. The long-term goal is to create a self-sustaining system that balances environmental preservation with agricultural productivity, providing both food and timber resources.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.3333074043118507, 29.90150936601325, 'OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg', 4, 1, ''),

('House in Construction in Gihosha', 83200000, 7240, 'Gihosha, Avenue du St Esprit, numero X', 1, 1, 'Located in an upscale neighborhood, this 7240 sqft residential construction site is set to become a gated community of modern, luxury homes. The project will include 50 high-end villas, each featuring contemporary designs with open floor plans, private pools, and landscaped gardens. The development will also offer amenities such as a clubhouse, fitness center, and children play areas. With utilities already connected and roads partially developed, this site is ready for construction.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.361838071340781, 29.3941623130847, 'OrtusRealty/listings/img12.webp,OrtusRealty/listings/img12.webp,OrtusRealty/listings/img12.webp,OrtusRealty/listings/img12.webp,OrtusRealty/listings/img12.webp', 3, 3, ''),

('Market Building in Bugarama(Looking For Investors)', 105000000, 6040, 'Bugarama, Mpehe, RN2', 3, 10, 'This 6040 sqft construction site is being developed into a large commercial market and retail center, set to include over 100 individual shops, restaurants, and cafes. The project design focuses on providing a vibrant shopping and dining experience with wide pedestrian walkways, covered outdoor seating, and ample parking. Located near a major highway, this commercial site will cater to the growing needs of the local community and attract shoppers from surrounding areas.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.293351608516207, 29.54775855242032, 'OrtusRealty/listings/img9_1.jpg,OrtusRealty/listings/img9_1.jpg,OrtusRealty/listings/img9_1.jpg,OrtusRealty/listings/img9_1.jpg,OrtusRealty/listings/img9_1.jpg', 4, 2, ''),

('One Family Apartment to Rent in Kugasaka', 800000, 1870, 'Kugasaka, Rue numero X', 2, 6, 'Located in a family-friendly neighborhood, this 4-bedroom, 3-bathroom home features an expansive living room, a modern kitchen with a breakfast nook, and a formal dining area. The master suite includes a walk-in closet and en-suite bathroom with a soaking tub. The backyard is fenced and includes a patio perfect for entertaining guests.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -2.913705735469025, 29.818157968031045, 'OrtusRealty/listings/img10_1.jpg,OrtusRealty/listings/img10_2.jpg,OrtusRealty/listings/img1_2.jpg,OrtusRealty/listings/img29.jpg,OrtusRealty/listings/img10_5.jpg', 2, 3, 'home3'),

('Commercial Land For Sale at Mushasha', 320100000, 8030, 'Mushasha, Avenue mushasha, Numero X', 1, 5, 'A 8030 sqft plot ideal for developing a modern office park or corporate headquarters. Located in a business-friendly zone with excellent access to highways, this land is perfect for professional services, tech companies, or multi-tenant office spaces. The area is surrounded by other commercial and office buildings, making it a hotspot for business development. The land is cleared and ready for construction, with water, electricity, and sewage connections in place.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.441319512707223, 29.931709489849013, 'OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg,OrtusRealty/listings/img2_4.jpg', 1, 2, ''),

('Farming Land in Gahoro', 310000, 3600, 'Nyabihanga, Muyebe, Gahoro', 2, 7, 'Spanning 3600 sqft, this certified organic-ready land offers pristine, chemical-free soil perfect for organic farming. The property is surrounded by natural vegetation, enhancing biodiversity and offering a buffer zone for organic practices. This land is ideal for small-scale or large-scale organic farming of fruits, vegetables, or herbs. The plot includes a small barn and a well for water access.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.397067156147256, 29.831877042751827, 'OrtusRealty/listings/img11.webp,OrtusRealty/listings/img11.webp,OrtusRealty/listings/img11.webp,OrtusRealty/listings/img11.webp,OrtusRealty/listings/img11.webp', 1, 1, ''),

('House in Construction For Sale in Kigobe', 218050000, 4302, 'Kigobe, Avenue kigobe, numero X', 1, 2, 'Located in an upscale neighborhood, this 4302 sqft residential construction site is set to become a gated community of modern, luxury homes. The project will include 50 high-end villas, each featuring contemporary designs with open floor plans, private pools, and landscaped gardens. The development will also offer amenities such as a clubhouse, fitness center, and children play areas. With utilities already connected and roads partially developed, this site is ready for construction.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.3655715310490604, 29.377497560498558, 'OrtusRealty/listings/img12.webp,OrtusRealty/listings/img12.webp,OrtusRealty/listings/img12.webp,OrtusRealty/listings/img12.webp,OrtusRealty/listings/img12.webp', 2, 3, ''),

('Market Construction Project in Nyabihanga Centre(Looking For investors)', 10000000, 5700, 'Nyabihanga, Centre', 3, 7, 'This 5700 sqft construction site is being developed into a large commercial market and retail center, set to include over 100 individual shops, restaurants, and cafes. The project design focuses on providing a vibrant shopping and dining experience with wide pedestrian walkways, covered outdoor seating, and ample parking. Located near a major highway, this commercial site will cater to the growing needs of the local community and attract shoppers from surrounding areas.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.4464824940326677, 29.76529892223461, 'OrtusRealty/listings/img9_1.jpg,OrtusRealty/listings/img9_1.jpg,OrtusRealty/listings/img9_1.jpg,OrtusRealty/listings/img9_1.jpg,OrtusRealty/listings/img9_1.jpg', 4, 2, ''),

('House For Renting at Mushasha', 500000, 1200, 'Mushasha, Avenue mushasha, numero X', 2, 5, 'This chic 2-bedroom, 2-bathroom urban loft is designed for modern living with an industrial flair. High ceilings, exposed brick walls, and large windows create a spacious, open atmosphere. The loft also includes a private balcony, a modern kitchen with stainless steel appliances, and access to communal amenities like a rooftop terrace and gym.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.4418228585855517, 29.929595909212082, 'OrtusRealty/listings/img15_1.jpg,OrtusRealty/listings/img15_2.jpg,OrtusRealty/listings/img15_3.jpg,OrtusRealty/listings/img5_5.jpg,OrtusRealty/listings/img15_5.jpg', 2, 3, 'home4'),

('Construction Site at Kugasaka', 230100000, 7300, 'Kugasaka, Avenue Kugasaka, Rue Numero X', 1, 6, 'This 7300 sqft construction site is being developed into a large commercial market and retail center, set to include over 100 individual shops, restaurants, and cafes. The project design focuses on providing a vibrant shopping and dining experience with wide pedestrian walkways, covered outdoor seating, and ample parking. Located near a major highway, this commercial site will cater to the growing needs of the local community and attract shoppers from surrounding areas.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -2.913099444237791, 29.81823225259782, 'OrtusRealty/listings/img8.jpg,OrtusRealty/listings/img8.jpg,OrtusRealty/listings/img8.jpg,OrtusRealty/listings/img8.jpg,OrtusRealty/listings/img8.jpg', 3, 2, ''),

('Multi-purpose Agricultural Land in Bugarama For Renting', 1000000, 8040, 'Bugarama', 2, 10, 'This 8040 sqft plot is a versatile agricultural property, suitable for a range of farming activities such as crop production, livestock grazing, or mixed farming. The land has a diverse terrain, with flat areas for planting and hilly sections perfect for raising cattle or other livestock. A river runs through the property, providing natural irrigation, and the land has convenient access to rural infrastructure and services.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.3092159365548692, 29.547259654723973, 'OrtusRealty/listings/img17_5.jpg,OrtusRealty/listings/img17_5.jpg,OrtusRealty/listings/img17_5.jpg,OrtusRealty/listings/img17_5.jpg,OrtusRealty/listings/img17_5.jpg', 1, 1, ''),

('Building in Construction Looking For Investors', 56700000, 6300, 'Kiriri, Avenue kiriri, Numero X', 3, 3, 'This prime 6300 sqft downtown site is being transformed into a multi-story, mixed-use commercial building. The development will feature office spaces on the upper floors, retail shops on the ground level, and underground parking. The modern design includes large glass facades, sustainable building materials, and green spaces integrated throughout the property. Positioned in a high-traffic area with easy access to public transportation, this site is ideal for businesses seeking a dynamic urban location.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.3938695948164326, 29.38436534250422, 'OrtusRealty/listings/img8.jpg,OrtusRealty/listings/img8.jpg,OrtusRealty/listings/img8.jpg,OrtusRealty/listings/img8.jpg,OrtusRealty/listings/img8.jpg', 4, 2, ''),

('Single Family House in Giheta For Sale', 340000000, 4500, 'Giheta, Murayi', 1, 8, 'Set on 10 acres of picturesque countryside, this 6-bedroom, 5-bathroom estate offers luxurious living with a touch of nature. The property includes a large swimming pool, a home office, a private gym, and a detached guesthouse. With spacious rooms and elegant finishes throughout, this estate is ideal for those who seek both comfort and space.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.2944402568308697, 29.82979198985505, 'OrtusRealty/listings/img19_1.jpg,OrtusRealty/listings/img10_2.jpg,OrtusRealty/listings/img19_3.jpg,OrtusRealty/listings/img1_2.jpg,OrtusRealty/listings/img29.jpg', 2, 3, 'home5'),

('FarmLand in Bukeye For Sale', 34500000, 5900, 'Bukeye, Gahaga', 1, 9, 'This beautiful 5900 sqft agricultural land is bordered by a freshwater river, making it ideal for both crop farming and livestock. The property boasts nutrient-rich soil and a natural irrigation system, offering excellent conditions for high-yield farming. The landscape includes gentle slopes, making it suitable for a variety of crops or a combination of crops and grazing land. With road access nearby, transportation of produce is efficient.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.1794629806765093, 29.64453213435479, 'OrtusRealty/listings/img20_1.jpg,OrtusRealty/listings/img20_1.jpg,OrtusRealty/listings/img20_1.jpg,OrtusRealty/listings/img20_1.jpg,OrtusRealty/listings/img20_1.jpg', 1, 1, ''),

('Apartment to Rent in Gihosha', 780000, 2040, 'Gihosha, Avenue gihosha, Numero X', 2, 1, 'This well-maintained 3-bedroom, 3-bathroom townhouse is perfect for those who want to enjoy suburban living with minimal maintenance. The open-concept design connects the living room, dining area, and kitchen, creating a warm and inviting space. The master bedroom includes an en-suite bathroom and walk-in closet. A private patio and attached garage add convenience and comfort.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.3693312172410397, 29.39862467184624, 'OrtusRealty/listings/img10_1.jpg,OrtusRealty/listings/img10_2.jpg,OrtusRealty/listings/img15_5.jpg,OrtusRealty/listings/img29.jpg,OrtusRealty/listings/img1_3.jpg', 2, 3, 'home6'),

('Warehouse For Sale (In Construction)', 680000000, 300000, 'Karera, Karera 2, Numero X', 1, 4, 'Spanning 25 acres, this commercial construction site is dedicated to the development of a state-of-the-art warehouse and distribution facility. The project will include a 300,000-square-foot warehouse with advanced storage systems, loading docks, and office space for administrative operations. The facility will also feature energy-efficient designs, including solar panels and water recycling systems, making it an eco-friendly distribution hub. With close proximity to major highways and rail links, this site is perfect for logistics and supply chain operations.|Placeholder content for this accordion, which is intended to demonstrate the class. This is the first item accordion body you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need.', -3.4225791902454867, 29.8932170921191, 'OrtusRealty/listings/img13.webp,OrtusRealty/listings/img13.webp,OrtusRealty/listings/img13.webp,OrtusRealty/listings/img13.webp,OrtusRealty/listings/img13.webp', 3, 2, ''),

('Apartments For Sale in Kigobe(Project in development)', 300000000, 1700, 'Kigobe, Avenue kigobe, Numero X', 1, 2, 'These will be 2-bedroom, 2-bathroom apartment features large windows that allow natural light to flood the space, this home includes an open-plan kitchen and living area, a spacious deck for outdoor dining, and a private beach access path. Ideal for a vacation home or full-time residence for those who want to live in an urban area.|Details about the site:  This centrally located 3-acre construction site is slated for a 30-story residential high-rise offering a mix of one- and two-bedroom apartments. The building will feature modern designs with energy-efficient fixtures, rooftop recreational areas, a fitness center, and underground parking. The site is near public transportation and major business districts, making it ideal for young professionals and urban dwellers. The foundation is already complete, and construction is moving ahead on schedule.', -3.36812627372743, 29.382101706368996, 'OrtusRealty/listings/img23_1.jpg,OrtusRealty/listings/img15_3.jpg,OrtusRealty/listings/img10_2.jpg,OrtusRealty/listings/img5_5.jpg,OrtusRealty/listings/img29.jpg', 2, 3, 'home7')

insert into home_details(home_details_id, home_category_id, num_of_beds, num_of_bathrooms, internal_features, external_features)
values('home1', 1, 3, 2, 'Fireplace in the living room,Office room,Master bedroom with en-suite bathroom', 'Garden space,Fenced backyard,Garage'),
('home2', 1, 5, 4, 'Floor-to-ceiling windows,Playroom,Master suite with walk-in closet,Home automation system', 'Garage,Swimming pool,Garden space,Gated community,24/7 security'),
('home3', 2, 4, 3, 'Central air conditioning and heating,Open-plan living and dining area,Master suite with walk-in closet,Central air conditioning and heating,Laundry room', 'Private balcony,Gym,Swimming pool'),
('home4', 1, 2, 2, 'Home automation system,Master bedroom with en-suite bathroom,Master suite with walk-in closet', 'Garage,Fenced backyard'),
('home5', 1, 6, 5, 'Office room,Playroom,Fireplace in the living room', 'Swimming pool,Gym,Garden space,Gated community,24/7 security,Parking'),
('home6', 2, 2, 3, 'Master suite with walk-in closet,Master bedroom with en-suite bathroom', 'Private balcony,24/7 security'),
('home7', 2, 2, 2, 'Floor-to-ceiling windows,Open-plan living and dining area,Central air conditioning and heating', 'Solar panels,Parking,Swimming Pool,Gym');


insert into important_facilities(infrastructure_name, infrastructure_type_id, nbhd_id)
values('Gihosha Hospital', 1, 1),
('Gihosha Medical Centre', 1, 1),
('Gihosha School', 2, 1),
('Gihosha Secondary Academy', 2, 1),
('Gihosha Shopping centre', 3, 1),
('Kigobe Shopping centre', 3, 2),
('Kigobe Mall', 3, 2),
('Kigobe School', 2, 2),
('Kigobe University', 2, 2),
('Kigobe Health Centre', 1, 2),
('Kiriri Hospital', 1, 3),
('Kiriri University', 2, 3),
('Kiriri Marketplace', 3, 3),
('Karera Mall', 3, 4),
('Karera Market', 3, 4),
('Karera primary school', 2, 4),
('Karera medical centre', 1, 4),
('Mushasha medical centre', 1, 5),
('Mushasha secondary school', 2, 5),
('Mushasha primary school', 2, 5),
('Kugasaka international school', 2, 6),
('Kugasaka Mall', 3, 6),
('Kugasaka shopping centre', 3, 6),
('Kugasaka shopping centre two', 3, 6),
('Kugasaka Health services', 1, 6),
('Kugasaka Hospital', 1, 6),
('Nyabihanga Hospital', 1, 7),
('Nyabihanga medical Centre', 1, 7),
('Nyabihanga University', 2, 7),
('Nyabihanga international academy', 3, 7),
('Nyabihanga shopping centre', 3, 7),
('Giheta Marketplace', 3, 8),
('Giheta Marketplace two', 3, 8),
('Giheta school', 2, 8),
('Giheta Hospital', 1, 8),
('Bukeye Hospital', 1, 9),
('Bukeye University', 2, 9),
('Bukeye academy', 2, 9),
('Bukeye Mall', 3, 9),
('Bugarama Market', 3, 10),
('Bugarama school', 2, 10),
('Bugarama Hospital', 1, 10),
('Bugarama medical centre', 1, 10),
('Bugarama health centre', 1, 10);


insert into internal_features(internal_feature, description)
values
('Fireplace in the living room', 'A cozy brick fireplace located in the living room, providing warmth and ambiance.'),
('Master bedroom with en-suite bathroom', 'A spacious master bedroom that includes a private bathroom.'),
('Floor-to-ceiling windows', 'Large windows that extend from the floor to the ceiling, offering abundant natural light and expansive views.'),
('Open-plan living and dining area', 'A combined living and dining space that creates a seamless flow between the two areas.'),
('Home automation system', 'A system that allows for the control of various home functions such as lighting, heating, and security through a centralized interface.'),
('Master suite with walk-in closet', 'A luxurious master bedroom that includes a large walk-in closet for ample storage.'),
('Central air conditioning and heating', 'A system that provides both cooling and heating throughout the home for year-round comfort.'),
('Office room', 'A dedicated room designed for work or study, equipped with necessary office furniture and amenities.'),
('Playroom', 'A room designated for children to play, often filled with toys and games.'),
('Laundry room', 'A room equipped with laundry appliances such as a washer and dryer, along with storage for cleaning supplies.');

insert into external_features(external_feature, description)
values
('Garage', 'A covered structure for parking vehicles, typically attached to or part of a house.'),
('Parking', 'Designated area or space for parking vehicles.'),
('Swimming pool', 'A large structure filled with water for swimming.'),
('Garden space', 'An area designated for growing plants, flowers, and vegetables.'),
('Gated community', 'A residential area with controlled access for residents and their guests.'),
('24/7 security', 'Security services provided around the clock to ensure safety and protection.'),
('Private balcony', 'A private outdoor space attached to a residence, typically accessible from a room.'),
('Gym', 'A facility equipped with exercise machines and weights for physical fitness.'),
('Fenced backyard', 'A backyard enclosed by a fence for privacy and security.'),
('Solar panels', 'Panels installed to convert sunlight into electricity for home use.');